name: TadikaApp
packages:
  SDWebImageSwiftUI:
    url: https://github.com/SDWebImage/SDWebImageSwiftUI
    from: 2.2.3
configs:
  TadikaApp-DEV: debug
  TadikaApp: release
configFiles:
  TadikaApp-DEV: Config/TadikaApp-DEV.xcconfig
  TadikaApp: Config/TadikaApp.xcconfig
settings:
  base:
    # USER DEFINED PROJECT
    BUILD_NUMBER: $(BUILD_NUMBER)
    VERSION_NAME: $(VERSION_NAME)
    CURRENT_PROJECT_VERSION: $(BUILD_NUMBER)
    MARKETING_VERSION: $(VERSION_NAME)
targets:
  TadikaApp:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: TadikaApp
        name: TadikaApp
    settings:
      base:
      # USER DEFINED TARGET
        INFOPLIST_FILE: TadikaApp/Info.plist
        GENERATE_INFOPLIST_FILE: NO
      configs:
        TadikaApp-DEV:
          PRODUCT_BUNDLE_IDENTIFIER: $(PRODUCT_BUNDLE_IDENTIFIER)
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
          PRODUCT_NAME: TadikaApp
          DEVELOPMENT_TEAM: MNPQBHRKTX
        TadikaApp:
          PRODUCT_BUNDLE_IDENTIFIER: $(PRODUCT_BUNDLE_IDENTIFIER)
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: RELEASE
          PRODUCT_NAME: TadikaApp
          DEVELOPMENT_TEAM: MNPQBHRKTX
    dependencies:
      - package: SDWebImageSwiftUI
schemes:
  TadikaApp:
    build:
      targets:
        TadikaApp: all
    run:
      config: TadikaApp
    profile:
      config: TadikaApp
    analyze:
      config: TadikaApp
    archive: TadikaApp
  TadikaApp-DEV:
    build:
      targets:
        TadikaApp: all
    run:
      config: TadikaApp-DEV
    profile:
      config: TadikaApp-DEV
    analyze:
      config: TadikaApp-DEV
    archive:
      config: TadikaApp-DEV
