name: Fishcus
packages:
  SDWebImageSwiftUI:
    url: https://github.com/SDWebImage/SDWebImageSwiftUI
    from: 2.2.3
configs:
  Fishcus-DEV: debug
  Fishcus: release
configFiles:
  Fishcus-DEV: Config/Fishcus-DEV.xcconfig
  Fishcus: Config/Fishcus.xcconfig
settings:
  base:
    # USER DEFINED PROJECT
    BUILD_NUMBER: $(BUILD_NUMBER)
    VERSION_NAME: $(VERSION_NAME)
    CURRENT_PROJECT_VERSION: $(BUILD_NUMBER)
    MARKETING_VERSION: $(VERSION_NAME)
targets:
  Fishcus:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: Fishcus
        name: Fishcus
    settings:
      base:
      # USER DEFINED TARGET
        INFOPLIST_FILE: Fishcus/Info.plist
        GENERATE_INFOPLIST_FILE: NO
      configs:
        Fishcus-DEV:
          PRODUCT_BUNDLE_IDENTIFIER: $(PRODUCT_BUNDLE_IDENTIFIER)
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
          PRODUCT_NAME: Fishcus
          DEVELOPMENT_TEAM: MNPQBHRKTX
        Fishcus:
          PRODUCT_BUNDLE_IDENTIFIER: $(PRODUCT_BUNDLE_IDENTIFIER)
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: RELEASE
          PRODUCT_NAME: Fishcus
          DEVELOPMENT_TEAM: MNPQBHRKTX
    dependencies:
      - package: SDWebImageSwiftUI
schemes:
  Fishcus:
    build:
      targets:
        Fishcus: all
    run:
      config: Fishcus
    profile:
      config: Fishcus
    analyze:
      config: Fishcus
    archive: Fishcus
  Fishcus-DEV:
    build:
      targets:
        Fishcus: all
    run:
      config: Fishcus-DEV
    profile:
      config: Fishcus-DEV
    analyze:
      config: Fishcus-DEV
    archive:
      config: Fishcus-DEV
